import 'package:json_annotation/json_annotation.dart';

part 'endpointslicelist_discovery_v1.g.dart';

///EndpointSliceList represents a list of endpoint slices
@JsonSerializable()
class EndpointslicelistDiscoveryV1 {
  ///APIVersion defines the versioned schema of this representation of an object. Servers
  ///should convert recognized schemas to the latest internal value, and may reject
  ///unrecognized values. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
  @JsonKey(name: 'apiVersion')
  ApiVersion? apiVersion;

  ///items is the list of endpoint slices
  @JsonKey(name: 'items')
  List<Item?> items;

  ///Kind is a string value representing the REST resource this object represents. Servers may
  ///infer this from the endpoint the client submits requests to. Cannot be updated. In
  ///CamelCase. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  @JsonKey(name: 'kind')
  EndpointslicelistDiscoveryV1Kind? kind;

  ///ListMeta describes metadata that synthetic resources must have, including lists and
  ///various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
  @JsonKey(name: 'metadata')
  EndpointslicelistDiscoveryV1Metadata? metadata;

  EndpointslicelistDiscoveryV1({
    this.apiVersion,
    required this.items,
    this.kind,
    this.metadata,
  });

  factory EndpointslicelistDiscoveryV1.fromJson(Map<String, dynamic> json) =>
      _$EndpointslicelistDiscoveryV1FromJson(json);

  Map<String, dynamic> toJson() => _$EndpointslicelistDiscoveryV1ToJson(this);
}

///APIVersion defines the versioned schema of this representation of an object. Servers
///should convert recognized schemas to the latest internal value, and may reject
///unrecognized values. More info:
///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
enum ApiVersion {
  @JsonValue('discovery.k8s.io/v1')
  DISCOVERY_K8_S_IO_V1,
}

final apiVersionValues = EnumValues({
  'discovery.k8s.io/v1': ApiVersion.DISCOVERY_K8_S_IO_V1,
});

@JsonSerializable()
class Item {
  ///addressType specifies the type of address carried by this EndpointSlice. All addresses in
  ///this slice must be the same type. This field is immutable after creation. The following
  ///address types are currently supported: * IPv4: Represents an IPv4 Address. * IPv6:
  ///Represents an IPv6 Address. * FQDN: Represents a Fully Qualified Domain Name.
  ///(Deprecated) The EndpointSlice controller only generates, and kube-proxy only processes,
  ///slices of addressType "IPv4" and "IPv6". No semantics are defined for the "FQDN" type.
  ///
  ///Possible enum values:
  ///- `"FQDN"` represents a FQDN.
  ///- `"IPv4"` represents an IPv4 Address.
  ///- `"IPv6"` represents an IPv6 Address.
  @JsonKey(name: 'addressType')
  AddressType addressType;

  ///APIVersion defines the versioned schema of this representation of an object. Servers
  ///should convert recognized schemas to the latest internal value, and may reject
  ///unrecognized values. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
  @JsonKey(name: 'apiVersion')
  ApiVersion? apiVersion;

  ///endpoints is a list of unique endpoints in this slice. Each slice may include a maximum
  ///of 1000 endpoints.
  @JsonKey(name: 'endpoints')
  List<Endpoint?> endpoints;

  ///Kind is a string value representing the REST resource this object represents. Servers may
  ///infer this from the endpoint the client submits requests to. Cannot be updated. In
  ///CamelCase. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  @JsonKey(name: 'kind')
  ItemKind? kind;

  ///ObjectMeta is metadata that all persisted resources must have, which includes all objects
  ///users must create.
  @JsonKey(name: 'metadata')
  ItemMetadata? metadata;

  ///ports specifies the list of network ports exposed by each endpoint in this slice. Each
  ///port must have a unique name. Each slice may include a maximum of 100 ports. Services
  ///always have at least 1 port, so EndpointSlices generated by the EndpointSlice controller
  ///will likewise always have at least 1 port. EndpointSlices used for other purposes may
  ///have an empty ports list.
  @JsonKey(name: 'ports')
  List<Port?>? ports;

  Item({
    required this.addressType,
    this.apiVersion,
    required this.endpoints,
    this.kind,
    this.metadata,
    this.ports,
  });

  factory Item.fromJson(Map<String, dynamic> json) => _$ItemFromJson(json);

  Map<String, dynamic> toJson() => _$ItemToJson(this);
}

///addressType specifies the type of address carried by this EndpointSlice. All addresses in
///this slice must be the same type. This field is immutable after creation. The following
///address types are currently supported: * IPv4: Represents an IPv4 Address. * IPv6:
///Represents an IPv6 Address. * FQDN: Represents a Fully Qualified Domain Name.
///(Deprecated) The EndpointSlice controller only generates, and kube-proxy only processes,
///slices of addressType "IPv4" and "IPv6". No semantics are defined for the "FQDN" type.
///
///Possible enum values:
///- `"FQDN"` represents a FQDN.
///- `"IPv4"` represents an IPv4 Address.
///- `"IPv6"` represents an IPv6 Address.
enum AddressType {
  @JsonValue('FQDN')
  FQDN,
  @JsonValue('IPv4')
  I_PV4,
  @JsonValue('IPv6')
  I_PV6,
}

final addressTypeValues = EnumValues({
  'FQDN': AddressType.FQDN,
  'IPv4': AddressType.I_PV4,
  'IPv6': AddressType.I_PV6,
});

@JsonSerializable()
class Endpoint {
  ///addresses of this endpoint. For EndpointSlices of addressType "IPv4" or "IPv6", the
  ///values are IP addresses in canonical form. The syntax and semantics of other addressType
  ///values are not defined. This must contain at least one address but no more than 100.
  ///EndpointSlices generated by the EndpointSlice controller will always have exactly 1
  ///address. No semantics are defined for additional addresses beyond the first, and
  ///kube-proxy does not look at them.
  @JsonKey(name: 'addresses')
  List<String?> addresses;

  ///EndpointConditions represents the current condition of an endpoint.
  @JsonKey(name: 'conditions')
  Conditions? conditions;

  ///deprecatedTopology contains topology information part of the v1beta1 API. This field is
  ///deprecated, and will be removed when the v1beta1 API is removed (no sooner than
  ///kubernetes v1.24).  While this field can hold values, it is not writable through the v1
  ///API, and any attempts to write to it will be silently ignored. Topology information can
  ///be found in the zone and nodeName fields instead.
  @JsonKey(name: 'deprecatedTopology')
  Map<String, String?>? deprecatedTopology;

  ///EndpointHints provides hints describing how an endpoint should be consumed.
  @JsonKey(name: 'hints')
  Hints? hints;

  ///hostname of this endpoint. This field may be used by consumers of endpoints to
  ///distinguish endpoints from each other (e.g. in DNS names). Multiple endpoints which use
  ///the same hostname should be considered fungible (e.g. multiple A values in DNS). Must be
  ///lowercase and pass DNS Label (RFC 1123) validation.
  @JsonKey(name: 'hostname')
  String? hostname;

  ///nodeName represents the name of the Node hosting this endpoint. This can be used to
  ///determine endpoints local to a Node.
  @JsonKey(name: 'nodeName')
  String? nodeName;

  ///ObjectReference contains enough information to let you inspect or modify the referred
  ///object.
  @JsonKey(name: 'targetRef')
  TargetRef? targetRef;

  ///zone is the name of the Zone this endpoint exists in.
  @JsonKey(name: 'zone')
  String? zone;

  Endpoint({
    required this.addresses,
    this.conditions,
    this.deprecatedTopology,
    this.hints,
    this.hostname,
    this.nodeName,
    this.targetRef,
    this.zone,
  });

  factory Endpoint.fromJson(Map<String, dynamic> json) =>
      _$EndpointFromJson(json);

  Map<String, dynamic> toJson() => _$EndpointToJson(this);
}

@JsonSerializable()
class Conditions {
  ///ready indicates that this endpoint is ready to receive traffic, according to whatever
  ///system is managing the endpoint. A nil value should be interpreted as "true". In general,
  ///an endpoint should be marked ready if it is serving and not terminating, though this can
  ///be overridden in some cases, such as when the associated Service has set the
  ///publishNotReadyAddresses flag.
  @JsonKey(name: 'ready')
  bool? ready;

  ///serving indicates that this endpoint is able to receive traffic, according to whatever
  ///system is managing the endpoint. For endpoints backed by pods, the EndpointSlice
  ///controller will mark the endpoint as serving if the pod's Ready condition is True. A nil
  ///value should be interpreted as "true".
  @JsonKey(name: 'serving')
  bool? serving;

  ///terminating indicates that this endpoint is terminating. A nil value should be
  ///interpreted as "false".
  @JsonKey(name: 'terminating')
  bool? terminating;

  Conditions({this.ready, this.serving, this.terminating});

  factory Conditions.fromJson(Map<String, dynamic> json) =>
      _$ConditionsFromJson(json);

  Map<String, dynamic> toJson() => _$ConditionsToJson(this);
}

@JsonSerializable()
class Hints {
  ///forNodes indicates the node(s) this endpoint should be consumed by when using topology
  ///aware routing. May contain a maximum of 8 entries.
  @JsonKey(name: 'forNodes')
  List<ForNode?>? forNodes;

  ///forZones indicates the zone(s) this endpoint should be consumed by when using topology
  ///aware routing. May contain a maximum of 8 entries.
  @JsonKey(name: 'forZones')
  List<ForZone?>? forZones;

  Hints({this.forNodes, this.forZones});

  factory Hints.fromJson(Map<String, dynamic> json) => _$HintsFromJson(json);

  Map<String, dynamic> toJson() => _$HintsToJson(this);
}

@JsonSerializable()
class ForNode {
  ///name represents the name of the node.
  @JsonKey(name: 'name')
  String name;

  ForNode({required this.name});

  factory ForNode.fromJson(Map<String, dynamic> json) =>
      _$ForNodeFromJson(json);

  Map<String, dynamic> toJson() => _$ForNodeToJson(this);
}

@JsonSerializable()
class ForZone {
  ///name represents the name of the zone.
  @JsonKey(name: 'name')
  String name;

  ForZone({required this.name});

  factory ForZone.fromJson(Map<String, dynamic> json) =>
      _$ForZoneFromJson(json);

  Map<String, dynamic> toJson() => _$ForZoneToJson(this);
}

@JsonSerializable()
class TargetRef {
  ///API version of the referent.
  @JsonKey(name: 'apiVersion')
  String? apiVersion;

  ///If referring to a piece of an object instead of an entire object, this string should
  ///contain a valid JSON/Go field access statement, such as
  ///desiredState.manifest.containers[2]. For example, if the object reference is to a
  ///container within a pod, this would take on a value like: "spec.containers{name}" (where
  ///"name" refers to the name of the container that triggered the event) or if no container
  ///name is specified "spec.containers[2]" (container with index 2 in this pod). This syntax
  ///is chosen only to have some well-defined way of referencing a part of an object.
  @JsonKey(name: 'fieldPath')
  String? fieldPath;

  ///Kind of the referent. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  @JsonKey(name: 'kind')
  String? kind;

  ///Name of the referent. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  @JsonKey(name: 'name')
  String? name;

  ///Namespace of the referent. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  @JsonKey(name: 'namespace')
  String? namespace;

  ///Specific resourceVersion to which this reference is made, if any. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
  @JsonKey(name: 'resourceVersion')
  String? resourceVersion;

  ///UID of the referent. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
  @JsonKey(name: 'uid')
  String? uid;

  TargetRef({
    this.apiVersion,
    this.fieldPath,
    this.kind,
    this.name,
    this.namespace,
    this.resourceVersion,
    this.uid,
  });

  factory TargetRef.fromJson(Map<String, dynamic> json) =>
      _$TargetRefFromJson(json);

  Map<String, dynamic> toJson() => _$TargetRefToJson(this);
}

///Kind is a string value representing the REST resource this object represents. Servers may
///infer this from the endpoint the client submits requests to. Cannot be updated. In
///CamelCase. More info:
///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
enum ItemKind {
  @JsonValue('EndpointSlice')
  ENDPOINT_SLICE,
}

final itemKindValues = EnumValues({'EndpointSlice': ItemKind.ENDPOINT_SLICE});

@JsonSerializable()
class ItemMetadata {
  ///Annotations is an unstructured key value map stored with a resource that may be set by
  ///external tools to store and retrieve arbitrary metadata. They are not queryable and
  ///should be preserved when modifying objects. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
  @JsonKey(name: 'annotations')
  Map<String, String?>? annotations;

  ///Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.
  ///Wrappers are provided for many of the factory methods that the time package offers.
  @JsonKey(name: 'creationTimestamp')
  DateTime? creationTimestamp;

  ///Number of seconds allowed for this object to gracefully terminate before it will be
  ///removed from the system. Only set when deletionTimestamp is also set. May only be
  ///shortened. Read-only.
  @JsonKey(name: 'deletionGracePeriodSeconds')
  int? deletionGracePeriodSeconds;

  ///Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.
  ///Wrappers are provided for many of the factory methods that the time package offers.
  @JsonKey(name: 'deletionTimestamp')
  DateTime? deletionTimestamp;

  ///Must be empty before the object is deleted from the registry. Each entry is an identifier
  ///for the responsible component that will remove the entry from the list. If the
  ///deletionTimestamp of the object is non-nil, entries in this list can only be removed.
  ///Finalizers may be processed and removed in any order.  Order is NOT enforced because it
  ///introduces significant risk of stuck finalizers. finalizers is a shared field, any actor
  ///with permission can reorder it. If the finalizer list is processed in order, then this
  ///can lead to a situation in which the component responsible for the first finalizer in the
  ///list is waiting for a signal (field value, external system, or other) produced by a
  ///component responsible for a finalizer later in the list, resulting in a deadlock. Without
  ///enforced ordering finalizers are free to order amongst themselves and are not vulnerable
  ///to ordering changes in the list.
  @JsonKey(name: 'finalizers')
  List<String?>? finalizers;

  ///GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF
  ///the Name field has not been provided. If this field is used, the name returned to the
  ///client will be different than the name passed. This value will also be combined with a
  ///unique suffix. The provided value has the same validation rules as the Name field, and
  ///may be truncated by the length of the suffix required to make the value unique on the
  ///server.
  ///
  ///If this field is specified and the generated name exists, the server will return a 409.
  ///
  ///Applied only if Name is not specified. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
  @JsonKey(name: 'generateName')
  String? generateName;

  ///A sequence number representing a specific generation of the desired state. Populated by
  ///the system. Read-only.
  @JsonKey(name: 'generation')
  int? generation;

  ///Map of string keys and values that can be used to organize and categorize (scope and
  ///select) objects. May match selectors of replication controllers and services. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
  @JsonKey(name: 'labels')
  Map<String, String?>? labels;

  ///ManagedFields maps workflow-id and version to the set of fields that are managed by that
  ///workflow. This is mostly for internal housekeeping, and users typically shouldn't need to
  ///set or understand this field. A workflow can be the user's name, a controller's name, or
  ///the name of a specific apply path like "ci-cd". The set of fields is always in the
  ///version that the workflow used when modifying the object.
  @JsonKey(name: 'managedFields')
  List<ManagedField?>? managedFields;

  ///Name must be unique within a namespace. Is required when creating resources, although
  ///some resources may allow a client to request the generation of an appropriate name
  ///automatically. Name is primarily intended for creation idempotence and configuration
  ///definition. Cannot be updated. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
  @JsonKey(name: 'name')
  String? name;

  ///Namespace defines the space within which each name must be unique. An empty namespace is
  ///equivalent to the "default" namespace, but "default" is the canonical representation. Not
  ///all objects are required to be scoped to a namespace - the value of this field for those
  ///objects will be empty.
  ///
  ///Must be a DNS_LABEL. Cannot be updated. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
  @JsonKey(name: 'namespace')
  String? namespace;

  ///List of objects depended by this object. If ALL objects in the list have been deleted,
  ///this object will be garbage collected. If this object is managed by a controller, then an
  ///entry in this list will point to this controller, with the controller field set to true.
  ///There cannot be more than one managing controller.
  @JsonKey(name: 'ownerReferences')
  List<OwnerReference?>? ownerReferences;

  ///An opaque value that represents the internal version of this object that can be used by
  ///clients to determine when objects have changed. May be used for optimistic concurrency,
  ///change detection, and the watch operation on a resource or set of resources. Clients must
  ///treat these values as opaque and passed unmodified back to the server. They may only be
  ///valid for a particular resource or set of resources.
  ///
  ///Populated by the system. Read-only. Value must be treated as opaque by clients and . More
  ///info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
  @JsonKey(name: 'resourceVersion')
  String? resourceVersion;

  ///Deprecated: selfLink is a legacy read-only field that is no longer populated by the
  ///system.
  @JsonKey(name: 'selfLink')
  String? selfLink;

  ///UID is the unique in time and space value for this object. It is typically generated by
  ///the server on successful creation of a resource and is not allowed to change on PUT
  ///operations.
  ///
  ///Populated by the system. Read-only. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
  @JsonKey(name: 'uid')
  String? uid;

  ItemMetadata({
    this.annotations,
    this.creationTimestamp,
    this.deletionGracePeriodSeconds,
    this.deletionTimestamp,
    this.finalizers,
    this.generateName,
    this.generation,
    this.labels,
    this.managedFields,
    this.name,
    this.namespace,
    this.ownerReferences,
    this.resourceVersion,
    this.selfLink,
    this.uid,
  });

  factory ItemMetadata.fromJson(Map<String, dynamic> json) =>
      _$ItemMetadataFromJson(json);

  Map<String, dynamic> toJson() => _$ItemMetadataToJson(this);
}

@JsonSerializable()
class ManagedField {
  ///APIVersion defines the version of this resource that this field set applies to. The
  ///format is "group/version" just like the top-level APIVersion field. It is necessary to
  ///track the version of a field set because it cannot be automatically converted.
  @JsonKey(name: 'apiVersion')
  String? apiVersion;

  ///FieldsType is the discriminator for the different fields format and version. There is
  ///currently only one possible value: "FieldsV1"
  @JsonKey(name: 'fieldsType')
  String? fieldsType;

  ///FieldsV1 stores a set of fields in a data structure like a Trie, in JSON format.
  ///
  ///Each key is either a '.' representing the field itself, and will always map to an empty
  ///set, or a string representing a sub-field or item. The string will follow one of these
  ///four formats: 'f:<name>', where <name> is the name of a field in a struct, or key in a
  ///map 'v:<value>', where <value> is the exact json formatted value of a list item
  ///'i:<index>', where <index> is position of a item in a list 'k:<keys>', where <keys> is a
  ///map of  a list item's key fields to their unique values If a key maps to an empty Fields
  ///value, the field that key represents is part of the set.
  ///
  ///The exact format is defined in sigs.k8s.io/structured-merge-diff
  @JsonKey(name: 'fieldsV1')
  Map<String, dynamic>? fieldsV1;

  ///Manager is an identifier of the workflow managing these fields.
  @JsonKey(name: 'manager')
  String? manager;

  ///Operation is the type of operation which lead to this ManagedFieldsEntry being created.
  ///The only valid values for this field are 'Apply' and 'Update'.
  @JsonKey(name: 'operation')
  String? operation;

  ///Subresource is the name of the subresource used to update that object, or empty string if
  ///the object was updated through the main resource. The value of this field is used to
  ///distinguish between managers, even if they share the same name. For example, a status
  ///update will be distinct from a regular update using the same manager name. Note that the
  ///APIVersion field is not related to the Subresource field and it always corresponds to the
  ///version of the main resource.
  @JsonKey(name: 'subresource')
  String? subresource;

  ///Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.
  ///Wrappers are provided for many of the factory methods that the time package offers.
  @JsonKey(name: 'time')
  DateTime? time;

  ManagedField({
    this.apiVersion,
    this.fieldsType,
    this.fieldsV1,
    this.manager,
    this.operation,
    this.subresource,
    this.time,
  });

  factory ManagedField.fromJson(Map<String, dynamic> json) =>
      _$ManagedFieldFromJson(json);

  Map<String, dynamic> toJson() => _$ManagedFieldToJson(this);
}

@JsonSerializable()
class OwnerReference {
  ///API version of the referent.
  @JsonKey(name: 'apiVersion')
  String apiVersion;

  ///If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot
  ///be deleted from the key-value store until this reference is removed. See
  ///https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion
  ///for how the garbage collector interacts with this field and enforces the foreground
  ///deletion. Defaults to false. To set this field, a user needs "delete" permission of the
  ///owner, otherwise 422 (Unprocessable Entity) will be returned.
  @JsonKey(name: 'blockOwnerDeletion')
  bool? blockOwnerDeletion;

  ///If true, this reference points to the managing controller.
  @JsonKey(name: 'controller')
  bool? controller;

  ///Kind of the referent. More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
  @JsonKey(name: 'kind')
  String kind;

  ///Name of the referent. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
  @JsonKey(name: 'name')
  String name;

  ///UID of the referent. More info:
  ///https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
  @JsonKey(name: 'uid')
  String uid;

  OwnerReference({
    required this.apiVersion,
    this.blockOwnerDeletion,
    this.controller,
    required this.kind,
    required this.name,
    required this.uid,
  });

  factory OwnerReference.fromJson(Map<String, dynamic> json) =>
      _$OwnerReferenceFromJson(json);

  Map<String, dynamic> toJson() => _$OwnerReferenceToJson(this);
}

@JsonSerializable()
class Port {
  ///The application protocol for this port. This is used as a hint for implementations to
  ///offer richer behavior for protocols that they understand. This field follows standard
  ///Kubernetes label syntax. Valid values are either:
  ///
  ///* Un-prefixed protocol names - reserved for IANA standard service names (as per RFC-6335
  ///and https://www.iana.org/assignments/service-names).
  ///
  ///* Kubernetes-defined prefixed names:
  ///* 'kubernetes.io/h2c' - HTTP/2 prior knowledge over cleartext as described in
  ///https://www.rfc-editor.org/rfc/rfc9113.html#name-starting-http-2-with-prior-
  ///* 'kubernetes.io/ws'  - WebSocket over cleartext as described in
  ///https://www.rfc-editor.org/rfc/rfc6455
  ///* 'kubernetes.io/wss' - WebSocket over TLS as described in
  ///https://www.rfc-editor.org/rfc/rfc6455
  ///
  ///* Other protocols should use implementation-defined prefixed names such as
  ///mycompany.com/my-custom-protocol.
  @JsonKey(name: 'appProtocol')
  String? appProtocol;

  ///name represents the name of this port. All ports in an EndpointSlice must have a unique
  ///name. If the EndpointSlice is derived from a Kubernetes service, this corresponds to the
  ///Service.ports[].name. Name must either be an empty string or pass DNS_LABEL validation: *
  ///must be no more than 63 characters long. * must consist of lower case alphanumeric
  ///characters or '-'. * must start and end with an alphanumeric character. Default is empty
  ///string.
  @JsonKey(name: 'name')
  String? name;

  ///port represents the port number of the endpoint. If the EndpointSlice is derived from a
  ///Kubernetes service, this must be set to the service's target port. EndpointSlices used
  ///for other purposes may have a nil port.
  @JsonKey(name: 'port')
  int? port;

  ///protocol represents the IP protocol for this port. Must be UDP, TCP, or SCTP. Default is
  ///TCP.
  ///
  ///Possible enum values:
  ///- `"SCTP"` is the SCTP protocol.
  ///- `"TCP"` is the TCP protocol.
  ///- `"UDP"` is the UDP protocol.
  @JsonKey(name: 'protocol')
  Protocol? protocol;

  Port({this.appProtocol, this.name, this.port, this.protocol});

  factory Port.fromJson(Map<String, dynamic> json) => _$PortFromJson(json);

  Map<String, dynamic> toJson() => _$PortToJson(this);
}

///protocol represents the IP protocol for this port. Must be UDP, TCP, or SCTP. Default is
///TCP.
///
///Possible enum values:
///- `"SCTP"` is the SCTP protocol.
///- `"TCP"` is the TCP protocol.
///- `"UDP"` is the UDP protocol.
enum Protocol {
  @JsonValue('SCTP')
  SCTP,
  @JsonValue('TCP')
  TCP,
  @JsonValue('UDP')
  UDP,
}

final protocolValues = EnumValues({
  'SCTP': Protocol.SCTP,
  'TCP': Protocol.TCP,
  'UDP': Protocol.UDP,
});

///Kind is a string value representing the REST resource this object represents. Servers may
///infer this from the endpoint the client submits requests to. Cannot be updated. In
///CamelCase. More info:
///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
enum EndpointslicelistDiscoveryV1Kind {
  @JsonValue('EndpointSliceList')
  ENDPOINT_SLICE_LIST,
}

final endpointslicelistDiscoveryV1KindValues = EnumValues({
  'EndpointSliceList': EndpointslicelistDiscoveryV1Kind.ENDPOINT_SLICE_LIST,
});

///ListMeta describes metadata that synthetic resources must have, including lists and
///various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
@JsonSerializable()
class EndpointslicelistDiscoveryV1Metadata {
  ///continue may be set if the user set a limit on the number of items returned, and
  ///indicates that the server has more data available. The value is opaque and may be used to
  ///issue another request to the endpoint that served this list to retrieve the next set of
  ///available objects. Continuing a consistent list may not be possible if the server
  ///configuration has changed or more than a few minutes have passed. The resourceVersion
  ///field returned when using this continue value will be identical to the value in the first
  ///response, unless you have received this token from an error message.
  @JsonKey(name: 'continue')
  String? metadataContinue;

  ///remainingItemCount is the number of subsequent items in the list which are not included
  ///in this list response. If the list request contained label or field selectors, then the
  ///number of remaining items is unknown and the field will be left unset and omitted during
  ///serialization. If the list is complete (either because it is not chunking or because this
  ///is the last chunk), then there are no more remaining items and this field will be left
  ///unset and omitted during serialization. Servers older than v1.15 do not set this field.
  ///The intended use of the remainingItemCount is *estimating* the size of a collection.
  ///Clients should not rely on the remainingItemCount to be set or to be exact.
  @JsonKey(name: 'remainingItemCount')
  int? remainingItemCount;

  ///String that identifies the server's internal version of this object that can be used by
  ///clients to determine when objects have changed. Value must be treated as opaque by
  ///clients and passed unmodified back to the server. Populated by the system. Read-only.
  ///More info:
  ///https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
  @JsonKey(name: 'resourceVersion')
  String? resourceVersion;

  ///Deprecated: selfLink is a legacy read-only field that is no longer populated by the
  ///system.
  @JsonKey(name: 'selfLink')
  String? selfLink;

  EndpointslicelistDiscoveryV1Metadata({
    this.metadataContinue,
    this.remainingItemCount,
    this.resourceVersion,
    this.selfLink,
  });

  factory EndpointslicelistDiscoveryV1Metadata.fromJson(
    Map<String, dynamic> json,
  ) => _$EndpointslicelistDiscoveryV1MetadataFromJson(json);

  Map<String, dynamic> toJson() =>
      _$EndpointslicelistDiscoveryV1MetadataToJson(this);
}

class EnumValues<T> {
  Map<String, T> map;
  late Map<T, String> reverseMap;

  EnumValues(this.map);

  Map<T, String> get reverse {
    reverseMap = map.map((k, v) => MapEntry(v, k));
    return reverseMap;
  }
}
