---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      pub:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      gomod:
        patterns:
          - "*"
